superflore/generators/ebuild/ebuild.py
Reverts allenh1/superflore#29
Unfortunately, bad things happened when I ran with this:
```
DESCRIPTION="'This package provides a set of typedef'"'"'s that allow
using Eigen datatypes in S'"
```
=> Revert "quoted description  string"

superflore/generators/ebuild/ebuild.py, superflore/utils.py
Deleting some characters lead to shitty looking descriptions.
Illegal characters can be reduced further to
```
"'`
```
only
=> quote instead of delete

superflore/generators/ebuild/ebuild.py, superflore/generators/ebuild/gen_packages.py
It's not great, but I can't think of a truly robust way to do this.
=> Adds a way to remove Python3 support from packages

superflore/generators/ebuild/gen_packages.py
I encountered some issues with Manifests that this should resolve. Some form of caching prevented the new tars from being downloaded.
=> Always remove an existing manifest when creating new ebuilds.

superflore/generators/ebuild/ebuild.py
This is along the lines of #55. This helps me from having to have to regenerate manifests all the time.
=> Add a distro-specific name to the archive name.

.travis.yml, setup.py, superflore/generators/ebuild/ebuild.py, superflore/generators/ebuild/run.py, superflore/rosdep_support.py, superflore/utils.py
This resolves keys using rosdep instead of parsing the yaml files by hand.
connects to #42, #7
=> Initial rosdep support for gentoo.

superflore/__init__.py, superflore/generators/bitbake/ros_meta.py, superflore/generators/ebuild/overlay_instance.py, superflore/generators/ebuild/run.py, superflore/repo_instance.py
=> Begin implementing the pr-only option.

superflore/generators/bitbake/run.py, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/overlay_instance.py, superflore/generators/ebuild/run.py, superflore/repo_instance.py
Fixes traceback for #50 
Current behavior just removes the symlinks. I should adapt this to remove the existing tmp directory as well.
connects to #50 
connects to #32
=> Remove os prefix from consecutive build error.

superflore/generate_installers.py, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/overlay_instance.py, superflore/generators/ebuild/run.py, superflore/repo_instance.py, superflore/utils.py
This set of changes adds an option to generate a single package by name, and will also include a refactor of `generate_packages.py` so that it can be relocated outside the `ebuild` folder (this will eliminate a lot of redundancy).
ToDo:
---------
=> Add `--only PKG` option

setup.py, superflore/docker.py, superflore/generators/ebuild/overlay_instance.py
This _should_ tell setup.py to install the dockerfile (so that we can have it in a central location and not run superflore from the source directory).
But I'm not sure where the file goes exactly?
> Each (directory, files) pair in the sequence specifies the installation directory and the files to install there. If directory is a relative path, it is interpreted relative to the installation prefix (Python’s sys.prefix for pure-Python packages, sys.exec_prefix for packages that contain extension modules). Each file name in files is interpreted relative to the setup.py script at the top of the package source distribution. No directory information from files is used to determine the final location of the installed file; only the name of the file is used.
This is from the [Python …
=> Add an install for the dockerfile.

.travis.yml, setup.py, superflore/__init__.py, superflore/generators/bitbake/yocto_recipe.py, superflore/generators/ebuild/ebuild.py, superflore/generators/ebuild/gen_packages.py, superflore/utils.py
This drops support for Python 2, since the `git-pull-request` utility doesn't work with Python 2.
=> Drop python 2

superflore/utils.py
Not anything _that_ important, but I noticed this generating a new set of Open Embedded recipes earlier.
=> Add missing '>' to info message.

superflore/generators/bitbake/yocto_recipe.py, superflore/generators/ebuild/ebuild.py, tests/ebuild/simple_expected.ebuild, tests/test_ebuild.py
This just allows for fewer characters to be present in the ebuilds/recipes, and is more Gentoo/Yocto-esque.
=> Replace vars where possible

repoman_docker/Dockerfile
This just adds a few commands to the `Dockerfile` that cause problems with (newer) versions of portage.
=> Fix an issue with the dockerfile.

superflore/generators/ebuild/gen_packages.py
As pointed out in ros/ros-overlay#279 by @flabrose, the `gpsd_client` packages were out of date.
This would explain why. I'm decently red in the face for not noticing this sooner.
=> Fix existing version detection.

superflore/generators/bitbake/yocto_recipe.py, tests/ebuild/simple_expected.ebuild
=> Replicated copyright change to open embedded, and resolved multi-license ToDo

superflore/generators/ebuild/overlay_instance.py
Really simple one here. Just seemed silly to have this `cd` command there.
=> Remove unnecessary 'cd' command in docker manifest regeneration.

superflore/CacheManager.py, superflore/HashManager.py, superflore/TempfileManager.py, superflore/generators/bitbake/gen_packages.py, superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py
This is an experiment to speed up the generation of OE recipes.
=> Add checksum cache

superflore/generators/bitbake/yocto_recipe.py, superflore/utils.py
This adds some deps for Open Embedded, as well as fixes some of the builds.
After this branch is merged, I think we'll do a release. This branch will be ready when catkin is cooperating completely.
=> Add more oe deps

superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/repo_instance.py
This pushes distros to their own branch, so we can keep them separate.
=> Distro specific branches

superflore/generators/bitbake/run.py, superflore/generators/ebuild/run.py
This adds the `--only [pkg_1] [pkg_2] ... [pkg_n]` argument to `superflore-gen-meta-pkgs`.
We also handle a `KeyError` exception in more graceful way than a backtrace.
=> Add `--only [pkg_1] [pkg_2] ... [pkg_n]`

tests/test_docker.py
This adds some test coverage for the docker file. The uncovered sections of the code are the `build` and `run` functions, which both depend on the docker command.
```
allenh1@hunter-laptop ~/work/superflore $ coverage run --source=superflore -m "nose" && coverage report -m 
.............................
Ran 29 tests in 1.892s
OK
superflore/TempfileManager.py                         34     23    32%   27-28, 31-41, 44-57
superflore/__init__.py …
```
=> Docker tests

tests/test_metadata_xml.py
This adds tests for `metadata_xml.py`. Currently, we just check that the xml parses.
=> Add metadata.xml tests.

superflore/generators/ebuild/ebuild.py
=> Add opencv3 check

superflore/utils.py, tests/test_utils.py
Mark certain functions with `# pragma: no cover` so that they don't get counted in the coverage results, as well as add a bit more to the license tests.
```
allenh1@hunter-laptop ~/work/superflore $ coverage run --source=superflore -m "nose" && coverage report -m
..............................
Ran 30 tests in 1.879s
OK
superflore/TempfileManager.py                         34     23    32%   27-28, 31-41, 44-57
superflore/__init__.py                                10 …
```
=> More utils tests

superflore/generators/ebuild/ebuild.py, tests/test_ebuild.py
Add a test to prevent this from happening in the future.
connects to #117.
=> Add test for ros-infrastructure/superflore#117.

superflore/generate_installers.py, superflore/generators/bitbake/run.py, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/run.py, superflore/utils.py
Work in progress!
connects to #116.
=> Add command line arguments to the PR text.

superflore/utils.py
@tfoote this removes the full path from the executable name.
see ros/ros-overlay#404
connects to #120, #116
=> Strip the path from the executable name.

.travis.yml, superflore/generators/bitbake/run.py, superflore/generators/ebuild/run.py
This adds a `--upstream-repo [url]` option to select where the PR is filed, and from where the repo is forked.
TODO: Open Embedded version.
connects to #49
=> Add `--upstream-repo` argument

superflore/generators/bitbake/gen_packages.py, superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py, superflore/generators/ebuild/overlay_instance.py, superflore/utils.py
This includes fies in the `files` directory as patches within the generated recipe text.
connects to #129
=> Adding patch file support for Open Embedded.

superflore/generators/bitbake/run.py, superflore/generators/ebuild/run.py, superflore/parser.py, superflore/utils.py
Work in progress!
So far, only the save and load logic has been centralized. Opening for visibility.
connects to #130.
=> Add --dry-run and --pr-only to Open Embedded

superflore/PackageMetadata.py, superflore/exceptions.py, superflore/generate_installers.py, superflore/generators/ebuild/ebuild.py, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/overlay_instance.py, superflore/generators/ebuild/run.py, superflore/utils.py, tests/test_utils.py
This is a work in progress still! I'm not super pleased with the quality of this patch.
But, in its current state, this _does_ add ROS 2 support, which is pretty neat.
=> Be My Ardent-tine

setup.py
This was an unfortunate typo (and oversight on my part), but is fortunately simple to fix.
=> Fix a typo blocking the Gentoo ebuild from working appropriately.

tests/test_generate_installers.py
This is the coverage with these changes.
```
...........................................
Ran 43 tests in 11.640s
OK
superflore/PackageMetadata.py                         22     18    18%   22-50
superflore/TempfileManager.py                         34     12    65%   32-37, 48-56
superflore/docker.py …
```
=> Added tests for generate_installers function.

tests/PackageXml/test.xml, tests/PackageXml/test2.xml, tests/test_PackageMetadata.py
Adds tests for the `PackageMetadata.py` file brought in by #134.
```
..............................................
Ran 46 tests in 12.760s
OK
superflore/PackageMetadata.py                         22      0   100%
superflore/TempfileManager.py                         34     12    65%   32-37, 48-56
superflore/docker.py …
```
=> Add tests for PackageMetadata.py.

tests/test_parser.py
This is an absolutely trivial thing to test, so I'll go ahead and add that extra 1% of coverage it gives us.
```
.............................................
Ran 45 tests in 14.358s
OK
superflore/PackageMetadata.py                         22     18    18%   22-50
superflore/TempfileManager.py                         34     12    65%   32-37, 48-56
superflore/__init__.py                                10 …
```
=> Added tests for parser.py.

tests/test_TempfileManager.py
```
..............................................
Ran 46 tests in 12.896s
OK
superflore/PackageMetadata.py                         22     18    18%   22-50
superflore/TempfileManager.py                         34      6    82%   48-56
superflore/docker.py                                  51     12    76%   40, 54-67, 77, 80-81 …
```
=> Add tests for TempfileManager

tests/test_utils.py
Working on unchecked exceptions.
=> Adding coverage for exceptions.py

tests/test_CacheManager.py
Adds testing for `CacheManger.py`.
```
..................................................
Ran 50 tests in 13.437s
OK
superflore/CacheManager.py                            20      0   100%
superflore/PackageMetadata.py                         22      0   100%
superflore/TempfileManager.py                         34      6    82%   48-56
superflore/docker.py                                  51     12    76%   40, 54-67, …
```
=> Add CacheManager tests.

.travis.yml, README.md, superflore/docker.py, superflore/test_integration/gentoo/build_base.py, superflore/test_integration/gentoo/main.py, tests/test_docker.py
This creates a logger mechanism for the docker container. We create a temporary directory using `TempfileManager`, then send the `stderr`and `stdout` streams into the file in append mode.
This allows us to grab the output even when commands return an error code, which is more desirable than just grabbing the output of successful commands (imo).
ToDo: parameterize the verbosity, add tests.
connects to #146
=> Create a way to get the log from the docker container.

superflore/utils.py, tests/test_utils.py
```
........................................................
Ran 56 tests in 14.888s
OK
superflore/CacheManager.py                            20      0   100%
superflore/PackageMetadata.py                         22      0   100%
superflore/TempfileManager.py                         34      6    82%   48-56
superflore/docker.py                                  78     23    71%   42, 56-69, 75, 93-95, 102, 107-108, …
```
=> Even more utils tests

superflore/utils.py, tests/test_utils.py
This one fixes the PR text properly. Again, not sure how I messed that one up.
=> Fix lack of command text in PR's.

stdeb.cfg
This will install it properly for debs.
=> Reference the LICENSE file from stdeb.cfg

superflore/generators/ebuild/ebuild.py, tests/ebuild/simple_expected.ebuild, tests/test_ebuild.py
This addresses https://github.com/ros/ros-overlay/issues/642
=> Support python3_6 for ROS 1

setup.py
Python 2 support was dropped in bf9d23bebf683fc09f1b7225713d7cc66a4df26c, but there doesn't seem to be any indication of this (besides lack of testing in Travis).
Also, I was able to install this for python 2 via pip.
Feel free to make the requirement a little more specific.
=> Enforce python 3 requirement

superflore/generate_installers.py, superflore/generators/bitbake/gen_packages.py, superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/overlay_instance.py, superflore/generators/ebuild/run.py, superflore/repo_instance.py, superflore/utils.py
Separating few cleanups from https://github.com/ros-infrastructure/superflore/pull/168 .
=> Small cleanups

superflore/generators/bitbake/ros_meta.py, superflore/generators/ebuild/overlay_instance.py, superflore/utils.py
Opened as an alternative to #171.
This PR reducing the amount of rosdistro hard-coding in commit message formatting. There is only one change in the generated text (unless I've made an error) which is that commit messages for ROS 2 distributions will now say `ros-ROSDISTRO, TIMESTAMP` rather than `ros2-ROSDISTRO, TIMEPSTAMP`. I believe this change to be acceptable given the simplification it enables.
I would have liked to remove the last hard-coded list of active ROS and ROS 2 distros but I only gave myself 10 minutes to make this change. I'd have no problem if @allenh1 or @andre-rosa wanted to address the TODO before this is merged. I do not know when I would have time to return to it.
In case we decide to merge the incremental improvement I also added dashing to the final hard-coded …
=> Reduce distro hardcoding

superflore/generators/bitbake/run.py, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/run.py, superflore/rosdep_support.py, superflore/test_integration/gentoo/main.py, superflore/utils.py
* Today Mon. Apr 8th we got 'dashing' alpha release
https://index.ros.org//doc/ros2/Releases/Release-Dashing-Diademata/
=> Use index for querying distro information

superflore/generate_installers.py, superflore/generators/bitbake/run.py, superflore/generators/ebuild/run.py, tests/test_generate_installers.py
* OpenEmbedded generation will need information from distro from
run.py, so allow run.py to get_distro() just once and pass it to
generate_installer(), like it's done for regenerate_installer().
=> Pass distro to generate_installer

superflore/exceptions.py, superflore/generate_installers.py, superflore/utils.py, tests/test_generate_installers.py, tests/test_utils.py
- Fixes #184 generating qt_metapackages recipes in Melodic
- Currently Proprietary and United States Government Purpose licenses
aren't matched in SuperFlore and it aborts generation of some melodic
packages like qt_metapackages/libqt_core
https://github.com/swri-robotics/qt_metapackages/blob/master/libqt_core/package.xml
- With the patch, license is output as:
...
LICENSE = "United States Government Purpose & SwRI Proprietary"
LIC_FILES_CHKSUM = "file://package.xml;beginline=11;endline=11;md5=8e473b26ead33548c945bdaca143a08d"
...
=> Pass along unknown licenses unclassified

superflore/generators/bitbake/gen_packages.py, superflore/generators/ebuild/gen_packages.py, superflore/utils.py, tests/test_utils.py
- Adds a retry mechanism to the XML downloads. It makes generation more
robust upon transient failures of the download which occurs more often
than not. Normally downloads work fine just by retrying them.
- Fixes #188 .
=> Retry XML downloads

superflore/generate_installers.py
generate_installers() didn't consider a few gen_pkg_func() failure
situations like:
- InvalidPackage:
The manifest contains invalid XML: syntax error: line 1, column 0
!!!! 61.7%: Failed to generate installer for package 'qb_chain'!
- NoPkgXml: Could not fetch pkg!
Those are signaled by gen_pkg_func by returning no installer (None)
and no missing dependencies ([]).
Whenever gen_pkg_func() returns no installer, it must be an error except
when we want to preserve_existing.
Fixes #186 .
=> Fix gen_pkg_func failure not being recorded by generate_installers

superflore/generate_installers.py
- Gentoo expects first checking for missing dependencies before
considering preserve_existing, so keep checks in that order.
=> Check missing dependencies before checking preserve_existing

superflore/generators/ebuild/overlay_instance.py
Add 'rosdistro sync' to the commit message when no rosdistro has been selected.
Signed-off-by: Hunter L. Allen <hunterlallen@protonmail.com>
connects to #195
=> Fix ros-None in Gentoo Commit Messages

.travis.yml
Use apt-get instead of apt for API stability
Signed-off-by: Hunter L. Allen <hunterlallen@protonmail.com>
---
see comments in #199
=> Change Back to apt-get for CI

superflore/generators/bitbake/yocto_recipe.py
- Like we already do for native recipes, avoid building in world
any recipes only present as <test_depends> of others.
=> Remove test-only components from world

superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/utils.py
- OpenEmbedded branches follow format: 'superflore/<DATETIME>' (UTC)
Fixes #211 .
=> Use branch based on UTC timestamp instead of random characters

setup.py
The old one is no longer accepted.
It's been shortened: https://pypi.org/classifiers/
HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: MIT Software License' is not a valid choice for this field for url: https://upload.pypi.org/legacy/
Signed-off-by: Tully Foote <tfoote@osrfoundation.org>
=> Update license classifier.

superflore/generate_installers.py, superflore/utils.py, tests/test_generate_installers.py, tests/test_utils.py
- Maintains current behavior where markdown is added by default
- PRs continue using markdown and commit descriptions will not
- Modify header formatting markdown for a more succinct syntax
Fixes #209 .
=> Make markdown optional for generating the PR and commit messages

superflore/utils.py, tests/test_utils.py
superflore currently generates commit messages that contain lines
starting with the markdown header indicator "#". However, commit message
lines that start with "#" are considered comments when amending a commit
and are removed unless the user remembers to quote them. Prevent these
lines from accidentally being removed by using the alternate form of
header indication: a line starting with "="-s or "-"-s underneath the
header text.
=> Prevent accidental removal of headers when amending a commit (#228)

superflore/generators/bitbake/yocto_recipe.py
ROS_SUPERFLORE_GENERATED_PLATFORM_PACKAGE_DEPENDENCIES is a list of
package names, not a list of recipes => add -native dependencies to it.
=> Include -native pkgs in list of OpenEmbedded platform dependencies (#230)

superflore/generators/bitbake/gen_packages.py
Fix a wild-card expansion that was accidentally matching more than just
version portion of recipe filenames.
=> Fix non-empty commit message for OpenEmbedded when no changes (#227)

superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py, superflore/generators/ebuild/overlay_instance.py
ROS_SUPERFLORE_GENERATED_PLATFORM_PACKAGE_DEPENDENCIES is a list of
package names, not a list of recipes => add -native dependencies to it.
=> Allow the timestamp associated with the run to be overridden (#231)

superflore/generate_installers.py, superflore/generators/bitbake/gen_packages.py, superflore/generators/ebuild/gen_packages.py, tests/test_generate_installers.py
What's being committed are recipes, so show their names instead of the
ROS package names in the commit and PR messages.
=> Show OpenEmbedded recipe names in commit and PR messages (#225)

superflore/generators/bitbake/run.py
* even when there aren't any changes in generated recipes
=> bitbake: create an commit when there are some other changes in generated files (#250)

README.md, superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/generators/ebuild/overlay_instance.py, superflore/generators/ebuild/run.py, superflore/parser.py
* useful when regenerating the files locally by hand without planing to submit
PR with the changes or when some other tool will do additional
integration before doing the PR (like we plan to do with meta-ros)
=> generators: add --no-branch option to prevent creating new local branch (#248)

README.md, superflore/exceptions.py, superflore/generators/bitbake/run.py, superflore/generators/ebuild/run.py, superflore/repo_instance.py
* to be able to generate the recipes locally without OAuth set
* currently it needs OAuth even when generating just locally and fails with:
meta-ros$ sh scripts/ros-generate-recipes.sh crystal
>>>> "crystal" distro detected...
args.output_repository_path: '.'
Traceback (most recent call last):
File "/usr/local/bin/superflore-gen-oe-recipes", line 11, in <module>
load_entry_point('superflore==0.2.1', 'console_scripts', 'superflore-gen-oe-recipes')()
File "/usr/local/lib/python3.6/dist-packages/superflore-0.2.1-py3.6.egg/superflore/generators/bitbake/run.py", line 98, in main
File "/usr/local/lib/python3.6/dist-packages/superflore-0.2.1-py3.6.egg/superflore/generators/bitbake/ros_meta.py", line 24, in __init__
File "/usr/local/lib/python3.6/dist-packages/superflore-0.2.1-py3.6.egg/superflore …
=> repo_instance: initialize gh_upstream only when creating pull request (#246)

superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py
* ros-generate-cache.sh already does that and superflore then just
generates recipes from cache.yaml file updated by
ros-generate-cache.sh
* fixes: https://github.com/ros-infrastructure/superflore/issues/252
* needs: https://github.com/ros/meta-ros/pull/643
=> yocto_recipe.py: don't create cache.yaml and cache.diffme (#252)

superflore/generators/bitbake/run.py
- The files under conf and files created by superflore-gen-oe-recipes
are only useful when all of the recipes for a ROS distro are being
generated => don't generate them when --only is specified.
- Use a slightly different commit message when --only is specified.
=> Change operation for OpenEmbedded when --only is specified (#224)

superflore/generate_installers.py, superflore/generators/bitbake/gen_packages.py, superflore/generators/ebuild/gen_packages.py
Use the terms "ebuild" and "recipe" instead of "installer" except in
names that are meant to refer to both.
=>  Use "ebuild"/"recipe" instead of "installer" (#226)

superflore/generators/bitbake/yocto_recipe.py
* superflore now with changes from:
https://github.com/ros-infrastructure/superflore/pull/256
generates the OE recipes according to ROS_SUPERFLORE_GENERATION_SCHEME 2
=> yocto_recipe.py: bump ROS_SUPERFLORE_GENERATION_SCHEME

superflore/generators/bitbake/yocto_recipe.py
=> yocto_recipe.py: Use sensible default for <build_type> when not ROS 1

setup.py
and small fix for superflore-datetime.inc.
=> Use "git describe" to append a local version label

README.md, superflore/generators/bitbake/run.py, superflore/parser.py
* there usually are some changes needed to manually adjust the .bbappends to build everything
correctly with the updated recipes, prevent people from accidentally creating pull-requests
on github before their changes and is ready to build (or even parse correctly)
=> bitbake: Don't create a pull request

superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py
=> bitbake: Fix path to cache.yaml in various places

superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py, superflore/generators/bitbake/yocto_recipe.py
* Now that there are two commits for every ROS distro release (one generated by ros-generate-cache and the other by superflore via ros-generate-recipes), having superflore attempt to generate a file that summarizes the changes introduced by the new release no longer makes sense (and what's being produced currently is useless) => drop the generation of superflore-change-summary.txt.
* Resolves #274.
=> bitbake:  Drop generation of superfore-change-summary.txt; fix exception message

README.md, superflore/generators/bitbake/run.py, superflore/parser.py, superflore/test_integration/gentoo/main.py, tests/test_parser.py
* Use keyword argument as
https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser
recommends.
* Otherwise it ends on first line of usage like bellow.
usage: Deploy ROS packages into OpenEmbedded Linux [-h]
[--ros-distro ROS_DISTRO]
--dry-run [--pr-only]
[--no-branch]
[--output-repository-path OUTPUT_REPOSITORY_PATH]
[--only ONLY [ONLY ...]]
[--pr-comment PR_COMMENT]
[--upstream-repo UPSTREAM_REPO]
[--upstream-branch UPSTREAM_BRANCH]
[--skip-keys SKIP_KEYS [SKIP_KEYS ...]]
[--tar-archive-dir TAR_ARCHIVE_DIR]
optional arguments:
...
instead of the expected:
usage: superflore-gen-oe-recipes [-h] [--ros-distro ROS_DISTRO] --dry-run
[--pr-only] [--no-branch]
[--output-repository-path OUTPUT_REPOSITORY_PATH]
[--only ONLY [ONLY ...]]
[--pr-comment PR_COMMENT]
[--upstream-repo …
=> parser.py: Show program name in usage message instead of description

superflore/generators/bitbake/gen_packages.py, superflore/generators/bitbake/ros_meta.py, superflore/generators/bitbake/run.py
* the overlay.repo.remove_file(existing, True) call in bitbake/gen_packages.py
works fine, but only when the new recipe is being generated in the same directory
as the previous version:
existing = glob.glob('{}_*.bb'.format(prefix))
where prefix is:
prefix = '{0}/meta-ros{1}-{2}/generated-recipes/{3}/{4}'
which will result in multiple recipes for the same package when the
package is moved to different prefix like pcl-conversions did for
dashing and eloquent:
```
meta-ros$ find . -name pcl-conversions\*bb
./meta-ros2-eloquent/generated-recipes/perception-pcl/pcl-conversions_2.1.0-1.bb
./meta-ros2-eloquent/generated-recipes/pcl-conversions/pcl-conversions_2.0.0-1.bb
./meta-ros1-melodic/generated-recipes/perception-pcl/pcl-conversions_1.7.0-2.bb …
```
=> superflore-gen-oe-recipes: Delete all generated files when regenerating all recipes

CHANGELOG.md, setup.py
Signed-off-by: Hunter L. Allen <hunter.allen@ghostrobotics.io>
@shr-project / @herb-kuta-lge  I need to generate the changelog, but this is step one... I'll set it up on my laptop and see how it goes.
---
Closes #283
=> Release 0.3.3

superflore/generators/bitbake/yocto_recipe.py
* generate new syntax for OE recipes to match:
https://lists.openembedded.org/g/openembedded-architecture/message/1260
https://lists.openembedded.org/g/openembedded-architecture/message/1279
https://lists.openembedded.org/g/openembedded-architecture/message/1291
* this was already done with conversion script in meta-ros with:
https://github.com/ros/meta-ros/pull/902
but for new ROS Distribution releases we want to generate new
syntax directly with superflore.
* it's not conditional based on OE release series, because all
currently supported versions (dunfell, hardknott, honister)
do support new syntax (when latest bitbake revision from
corresponding branch is being used).
* fixes https://github.com/ros-infrastructure/superflore/issues/284
=> bitbake: generate new overrides syntax

.github/workflows/ci.yaml, requirements.txt
I saw that you asked for the CI workflow to be updated for #299 
I did a quick run at making the necessary changes.  The commits are clean however since I was working in the GHA workflow editor some commits failed and had to be corrected.  (eg switching from nose to nose3 then to pynose) I am happy to rework the series if you feel it is necessary.
You may see the workflow test runs I did here: https://github.com/robwoolley/superflore/actions
=> Update GitHub Actions workflow

superflore/generators/ebuild/gen_packages.py
ebuild generation was not utilizing package conditions.
Packages with multiple build types were causing hard failures during
ebuild generation but it's possible that invalid ebuilds were being
generated for other packages as well due to the lack of dependency
conditions.
Fixes #289.
=> Evaluate package conditions when generating ebuilds

docker/Dockerfile, requirements.txt, setup_superflore.sh, superflore/generators/ebuild/gen_packages.py, superflore/generators/ebuild/overlay_instance.py
This Docker container is based on the osrf/ros2:devel container image.  It adds the additional dependencies required to develop superflore.
It may be used independently, but it is intended for use as a VSCode devcontainer for development of superflore.
=> Add Docker container for development

superflore/generators/bitbake/run.py, superflore/generators/ebuild/run.py, superflore/generators/nix/run.py
When --only is used, if --dry-run is used it calls save_pr(), otherwise file_pr() is called. This fix ensures that the same string value is passed to the delta parameter of both functions.
The call to save_pr was incorrectly passing the list args.only instead of the string delta which contains the contents of args.only
This caused a TypeError exception in get_pr_text when concatenating the list to a string.
File ".../superflore/superflore/utils.py", line 59, in get_pr_text
msg += '\n' + delta + '\n'
~~~~~^~~~~~~
TypeError: can only concatenate str (not "list") to str
=> Set correct pull request message for --dry-run case
