ros-infrastructure/superflore

- ebuild_generator/ebuild.py
- ebuild_generator/gen_packages.py
Some mistakes were made while linting, and this fixes them.
> Fixes some problems I created in the process of linting.

- ebuild_generator/ebuild.py
> dynamic slot

- ebuild_generator/ebuild.py
> removed logical or

- .gitignore
- LICENSE
- ebuild_generator/ebuild.py
- ebuild_generator/gen_packages.py
- ebuild_generator/metadata_xml.py
- ebuild_generator/repo_instance.py
- run.py
- tests/test_code_format.py
License this repo under Apache 2.0.
> Added license.

- superflore/generators/ebuild/ebuild.py
Removes the hard coded python versions entirely!
> Fix python

- superflore/generators/ebuild/ebuild.py
fixes https://github.com/allenh1/superflore/issues/3
> quoted description  string

- superflore/generators/ebuild/ebuild.py
- superflore/utils.py
This is a fix for the obnoxious characters that are sometimes in the package.xml descriptions.
connects to #3
> Adds a sanitizer function

- superflore/generators/ebuild/gen_packages.py
- superflore/generators/ebuild/metadata_xml.py
- superflore/generators/ebuild/run.py
> Add longdescription to metadata 84

- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/metadata_xml.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
> Implemented argument parsing using argparse.

- setup.py
- superflore/exceptions.py
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/yocto_recipe.py
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/run.py
- superflore/utils.py
Just cleaning up in preparation for #42
> Centralizing the dependency resolution to ease transition to rosdep.

- repoman_docker/Dockerfile
- superflore/docker.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
> Starting to implement docker integration.

- superflore/generators/bitbake/gen_packages.py
- superflore/generators/ebuild/gen_packages.py
fixes #47.
I think I got too crafty while avoiding the linter.
> Add package name to progress update.

- superflore/generators/ebuild/ebuild.py
- superflore/utils.py
This cleans up the truncation a little better.
connects to #35
> Trim description to 80, and end with '[...]'

- .gitignore
- .travis.yml
- superflore/docker.py
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/ros_meta.py
- superflore/generators/bitbake/run.py
- superflore/generators/bitbake/yocto_recipe.py
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
- superflore/repo_instance.py
- superflore/rosdep_support.py
- superflore/utils.py
- tests/test_code_format.py
Adds pep8 to the required tests.
connects to #57
> Adding pep8 to the tests

- README.md
Adds more info to the readme.
connects to #54
> Add more detailed usage information.

- setup.py
From list here: https://pypi.python.org/pypi?%3Aaction=list_classifiers
> Use appropriate classifier

- superflore/generators/ebuild/ebuild.py
This should work -- I'll need to test it, since there were no updates today (strange!).
> Remove Extra Newlines

- .travis.yml
- setup.py
- superflore/docker.py
Opening for viability.
connects to ros-infrastructure/superflore#66
> Use upstream docker 66

- .travis.yml
- requirements.txt
- superflore/__init__.py
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/ros_meta.py
- superflore/generators/bitbake/run.py
- superflore/generators/bitbake/yocto_recipe.py
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
- superflore/repo_instance.py
- superflore/utils.py
More python3/python2 confusion.
> Fix Nosetests invocation in CI

- superflore/utils.py
- tests/test_utils.py
Tests:
---------
Documentation:
----------------------
> Add test_utils.py file to start implementing tests.

- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/run.py
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
- superflore/generators/ebuild/run.py
New linter errors are showing up on master (I guess Flake8 updated?).
> Fix Linter Errors

- superflore/TempfileManager.py
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/ros_meta.py
- superflore/generators/bitbake/run.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
- superflore/repo_instance.py
- superflore/utils.py
This is the Open Embedded side of #76's changes.
> Feature Parity for Open Embedded

- superflore/generate_installers.py
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/run.py
- superflore/generators/bitbake/yocto_recipe.py
This was much easier than I thought it was going to be.
Connects to #80
> Remove tar file after use.

- README.md
- superflore/TempfileManager.py
- superflore/docker.py
- superflore/generate_installers.py
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/ros_meta.py
- superflore/generators/bitbake/run.py
- superflore/generators/bitbake/yocto_recipe.py
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
- superflore/repo_instance.py
- superflore/rosdep_support.py
- superflore/utils.py
> Add list of depend-only packages to the ebuild generator.

- superflore/utils.py
- tests/test_utils.py
> Add public domain license

- .gitignore
- .travis.yml
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
- superflore/generators/ebuild/run.py
- tests/ebuild/simple_expected.ebuild
- tests/test_ebuild.py
This PR adds tests for the ebuilds that are generated.
connects to #72
> Unit tests for Ebuilds

- superflore/generate_installers.py
- superflore/generators/ebuild/ebuild.py
Instead of just a bare except, the exception should be caught and handled appropriately.
> Catch unknown license

- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/run.py
There was a minor problem with the `--ros-distro` flag not doing what it was supposed to do. This fixes that.
> Fix OE generation.

- superflore/utils.py
Minor change -- just removes an extra argument to the `err` function.
> Remove extra argument to err call.

- CHANGELOG.md
- setup.py
Bump version in preparation to release.
> Bump version to 0.2.0

- superflore/generators/bitbake/run.py
- superflore/generators/ebuild/run.py
- superflore/repo_instance.py
- superflore/utils.py
This changes the style of the ebuild comments to be more human-readable, as suggested by @tfoote.
connects to #119
> More Explicit PRs

- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
This adds the `USE` flag `test` which pulls in test dependencies when enabled.
> Add in test dependencies, enabled by the use flag 'test'

- CHANGELOG.md
- setup.py
> Bump version to 0.2.1.

- README.md
- requirements.txt
- setup.py
- superflore/exceptions.py
- superflore/generators/ebuild/run.py
- superflore/repo_instance.py
- tests/test_code_format.py
Use the GitHub API to file PRs, removing the `git-pull-request` dependency.
connects to #67
> Use GitHub api instead of the Git Pull Request module

- stdeb.cfg
@allenh1 This ran through for me with one fix to the comma separation.
> fixing comma separated list in stdeb file

- setup.py
- stdeb.cfg
I couldn't re-open the other PR, but could (somehow) restore the deleted branch.
This is updated and has been rebased on top of the current master. I'm going to try it out in a container.
connects to #78
> Add stdeb.cfg

- superflore/generators/ebuild/overlay_instance.py
- superflore/utils.py
There's just a small issue after this one, and I think we'll do a patch release.
> Add Melodic to list

- stdeb.cfg
> Add bionic to stdeb.cfg.

- superflore/utils.py
This adds bouncy to the ROS 2 distro list.
> Add bouncy

- .travis.yml
- superflore/generators/bitbake/gen_packages.py
- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/gen_packages.py
- superflore/utils.py
Adds generation of ROS 2 Crystal.
> Add Crystal Distribution

- superflore/generators/ebuild/metadata_xml.py
I need to update this to my current email so that any bugs that get logged upstream get directed to me.
> Fix maintainer email

- superflore/generators/ebuild/run.py
Removes the ROS 2 index.
connects to #162
> Remove ROS 2 index, since it is now part of the conventional one.

- superflore/generators/ebuild/ebuild.py
- superflore/utils.py
@allenh1  << Are you able to verify that passing the distro parameter to resolve_rosdep_key in 'gentoo' case works well too?
> Add distro parameter to resolve_dep

- superflore/generators/ebuild/gen_packages.py
Small issue introduced by #171.
ros/ros-overlay#782 was generated with this patch.
> Fix small syntax issue

- superflore/generators/bitbake/gen_packages.py
- superflore/generators/bitbake/run.py
* Like in ebuild, for consistency's sake.
> Rename regenerate_installer to regenerate_pkg

- superflore/generators/bitbake/ros_meta.py
- superflore/generators/bitbake/run.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
- distro could never be 'all' after all
> Fix args.all handling

- superflore/generators/bitbake/yocto_recipe.py
- superflore/utils.py
- tests/test_utils.py
> Add superflore version to ros-distro.inc

- superflore/repo_instance.py
- superflore/utils.py
> Retry pushing when wrong credentials are provided or there's an error

- superflore/generators/bitbake/ros_meta.py
- superflore/generators/bitbake/run.py
- superflore/generators/ebuild/overlay_instance.py
- superflore/generators/ebuild/run.py
- Allows the caller to customize the pull request title as needed
Fixes #215 .
> Add an optional title parameter to the overlay pull_request method

- superflore/generators/bitbake/run.py
- If dependencies can't be found by rosdep mappings nor in OpenEmbedded
layers index, it'll be converted to OE naming and output always.
Fixes #217 .
> Don't output missing dependencies for OpenEmbedded

- superflore/generators/ebuild/metadata_xml.py
Change to my personal email.
Signed-off-by: Hunter L. Allen <hunterlallen@protonmail.com>
> Change to Personal Email

- .travis.yml
Upgrade ubuntu to bionic, and upgrade python versions to 3.7 and 3.8
Signed-off-by: Hunter L. Allen <hunterlallen@protonmail.com>
---
Connects to #239
> Upgrade CI

- README.md
- superflore/generators/bitbake/run.py
- superflore/parser.py
* enforce the requirement in the parser like --dry-run does now
> bitbake/run.py: Require --ros-distro

- CHANGELOG.md
- setup.py
Release of superflore version 0.3.2.
@shr-project / @herb-kuta-lge thank you both so much for all your work!
> Release 0.3.2

- superflore/generators/ebuild/ebuild.py
- superflore/generators/ebuild/overlay_instance.py
Signed-off-by: Hunter L. Allen <hunter.allen@ghostrobotics.io>
> Noetic support For Gentoo
